# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 06:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170225_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutchorder',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dutchorder',
            name='reserve_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 27, 3, 30, 45, 1904)),
        ),
    ]
