# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 06:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170226_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutchorder',
            name='reserve_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 27, 3, 31, 27, 59998)),
        ),
    ]
