# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 06:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170226_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutchorder',
            name='reserve_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 26, 18, 34, 13, 747493, tzinfo=utc)),
        ),
    ]
