# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170226_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutchorder',
            name='reserve_at',
            field=models.DateTimeField(default=main.models.default_time),
        ),
    ]
