# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170226_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutchorder',
            name='reserve_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
