# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_mainimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainimage',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
