# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_mainimage_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainimage',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
