# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('name_eng', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('hot', models.BooleanField(default=True)),
                ('warm', models.BooleanField(default=False)),
                ('ice', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('on_sale', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id', 'name_eng'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Desert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('name_eng', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.PositiveIntegerField()),
                ('on_sale', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Category')),
            ],
        ),
        migrations.CreateModel(
            name='HandDrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=120)),
                ('region_eng', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('name_eng', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('on_sale', models.BooleanField(default=True)),
                ('roasting_date', models.DateField()),
                ('start_sale_date', models.DateField(auto_now_add=True, null=True)),
                ('end_sale_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-roasting_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='beverage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Category'),
        ),
    ]
