# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.PositiveIntegerField(max_length=5)),
                ('description', models.TextField()),
                ('on_sale', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HandDrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(max_length=5)),
                ('on_sale', models.BooleanField(default=True)),
                ('roasting_date', models.DateTimeField()),
            ],
        ),
    ]
