# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverage',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='handdrip',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
