# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20170212_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('name_eng', models.CharField(blank=True, max_length=120, null=True)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('on_sale', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Desert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('name_eng', models.CharField(blank=True, max_length=120, null=True)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('on_sale', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('name_eng', models.CharField(blank=True, max_length=120, null=True)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('on_sale', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Beverage',
        ),
        migrations.AddField(
            model_name='handdrip',
            name='name_eng',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='handdrip',
            name='region_eng',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
