# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20170216_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('name_eng', models.CharField(blank=True, max_length=120, null=True)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('on_sale', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Coffee',
        ),
        migrations.DeleteModel(
            name='Desert',
        ),
        migrations.DeleteModel(
            name='Tea',
        ),
        migrations.AddField(
            model_name='beverage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Category'),
        ),
    ]
