# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20170218_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beverage',
            options={'ordering': ['id', 'name_eng']},
        ),
        migrations.AlterModelOptions(
            name='handdrip',
            options={'ordering': ['id', 'name_eng']},
        ),
        migrations.AddField(
            model_name='beverage',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beverage',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='beverage',
            name='name_eng',
            field=models.CharField(default=1, max_length=120, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='handdrip',
            name='region_eng',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
