# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20170218_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverage',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
