# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20170218_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='hot',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='beverage',
            name='ice',
            field=models.BooleanField(default=True),
        ),
    ]
