# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20170219_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('name_eng', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.PositiveIntegerField()),
                ('on_sale', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Category')),
            ],
        ),
        migrations.AlterModelOptions(
            name='handdrip',
            options={'ordering': ['-roasting_date', '-id']},
        ),
        migrations.AddField(
            model_name='handdrip',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='beverage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handdrip',
            name='roasting_date',
            field=models.DateField(),
        ),
    ]
