# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20170222_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handdrip',
            name='name_eng',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
