# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_auto_20170222_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='warm',
            field=models.BooleanField(default=False),
        ),
    ]
