# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_beverage_warm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desert',
            options={'ordering': ['id']},
        ),
    ]
