# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_auto_20170304_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desert',
            options={},
        ),
        migrations.AddField(
            model_name='handdrip',
            name='end_sale_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handdrip',
            name='start_sale_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
