# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_auto_20170309_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handdrip',
            name='end_sale_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handdrip',
            name='start_sale_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
